/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.htamakos;

import java.util.HashMap;
import java.util.Optional;

class Solution {
    public int[] twoSum1(int[] nums, int target) {
        int i = 0, j = 0;

        for (int v1 : nums) {
            for (j = i + 1; j < nums.length; j++) {
                int v2 = nums[j];
                if ((v1 + v2) == target) {
                    return (new int[] {i, j});
                }
            }
            i++;
        }

        return (new int[] {});
    }

    public int[] twoSum2(int[] nums, int target) {
        HashMap<Integer, Integer> h = new HashMap<Integer, Integer>();

        int i = 0;
        for (int v : nums) {
            h.put(v, i);
            i++;
        }

        int key1 = 0, key2 = 0;
        for (int v : nums) {
            Optional<Integer> n_key = Optional.ofNullable(h.get(target - v));
            key2 = n_key.orElse(0);

            if (n_key.isPresent() && key2 != key1) {
                return new int[] {key1, key2};
            }
            key1++;
        }

        return new int[] {};
    }
}
