/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.htamakos;

import static org.junit.Assert.*;

import org.junit.Test;

public class SolutionTest {
    @Test
    public void testTwoSum() {
        int[] nums = {3, 3};
        int target = 6;
        int[] ans = {0, 1};

        Solution s = new Solution();
        assertArrayEquals(ans, s.twoSum1(nums, target));
        assertArrayEquals(ans, s.twoSum2(nums, target));
    }

    @Test
    public void testTwoSum2() {
        int[] nums = {2, 5, 5, 11};
        int target = 10;
        int[] ans = {1, 2};

        Solution s = new Solution();
        assertArrayEquals(ans, s.twoSum1(nums, target));
        assertArrayEquals(ans, s.twoSum2(nums, target));
    }
}
